## Question 1

Implement a function for counting the number of boxes N(є) of side length є needed to cover a two-dimensional trajectory of a dynamical system.  Your code should take the trajectory and an є; it should output N(є).

Download the following trajectory of the Lorenz system from:

http://tuvalu.santafe.edu/~jgarland/CapDimData.dat

The first column is the x-coordinate, the second the y-coordinate, and the third the z-coordinate.  While the trajectory is three-dimensional, we will only use various two-dimensional projections in this homework in order to make things simple.  The later problems in this homework concern the effects that that projection has upon the fractal dimension.

#### (a)

Using an x, z projection (i.e., only the x and z coordinates) of this trajectory, with є = 0.01, what is N(є)?  Your answer may vary a bit from the numbers below; if so, choose the one that's closest to what you got.

    A. 12,163

    B. 4,342

    C. 13,998

    D. 1

    E. 745
    
#### (b)

Would the point (log(1 / 0.01), log(N(0.01))) be in the scaling region of a log(N(є)) versus log(1/є) plot for this trajectory?


    A. Most likely


    B. No, all points are covered by a single box


    C. No, all points are covered by (approximately) their own box


#### (c)

Again using an x, z projection of this trajectory, but with є = 0.5, find N(є).  Your answer may vary a bit from the numbers below; if so, choose the one that's closest to what you got.


    A. 12,163


    B. 4,342


    C. 3,106


    D. 5


    E. 14,000


#### (d)

Would the point (log(1 / 0.5), log(N(0.5))) be in the scaling region of a log(N(є)) versus log(1/є) plot for this trajectory?


    A. Most likely


    B. No, all points are covered by a single box


    C. No, all points are covered by (approximately) their own box


In [4]:
using Plots

In [6]:
plotlyjs()

Plots.PlotlyJSBackend()

In [1]:
CapDimData = readdlm("CapDimData.dat", '\,')

14000×3 Array{Float64,2}:
 -12.139  -18.644  30.953
 -12.243  -18.796  31.057
 -12.348  -18.948  31.165
 -12.454  -19.1    31.276
 -12.561  -19.252  31.391
 -12.668  -19.403  31.509
 -12.776  -19.555  31.63 
 -12.885  -19.706  31.755
 -12.995  -19.857  31.884
 -13.105  -20.007  32.016
 -13.216  -20.157  32.152
 -13.327  -20.306  32.292
 -13.439  -20.455  32.435
   ⋮                     
 -15.698  -21.85   38.198
 -15.797  -21.933  38.389
 -15.895  -22.015  38.583
 -15.992  -22.093  38.78 
 -16.09   -22.169  38.98 
 -16.187  -22.243  39.182
 -16.284  -22.313  39.386
 -16.38   -22.381  39.593
 -16.476  -22.445  39.803
 -16.571  -22.507  40.015
 -16.666  -22.566  40.229
 -16.76   -22.621  40.445

In [9]:
plot3d(CapDimData[:,1], CapDimData[:, 2], CapDimData[:, 3])

In [8]:
plot(CapDimData[:,1], CapDimData[:, 2])

In [39]:
CapDimData[:, 2]

14000-element Array{Float64,1}:
 -18.644
 -18.796
 -18.948
 -19.1  
 -19.252
 -19.403
 -19.555
 -19.706
 -19.857
 -20.007
 -20.157
 -20.306
 -20.455
   ⋮    
 -21.85 
 -21.933
 -22.015
 -22.093
 -22.169
 -22.243
 -22.313
 -22.381
 -22.445
 -22.507
 -22.566
 -22.621

In [70]:
function Num_boxes_2D(A, ɛ, x::Int, y::Int)
    
    mins = zeros(length(A[1,:]))
    maxs = zeros(length(A[1,:]))

    for i in 1:length(A[1,:])
        
        maxs[i] = maximum(A[:, i])
        mins[i] = minimum(A[:, i])
        
    end
    
    Box_matrix = zeros(ceil(Int, (maxs[x] - mins[x])/ɛ) + 1, ceil(Int, (maxs[y] - mins[y])/ɛ) + 1)
    
    for i in 1:length(A[:, 1])
        
        x_cur = ceil(Int, (A[i, x] - mins[x])/ɛ) + 1
        y_cur = ceil(Int, (A[i, y] - mins[y])/ɛ) + 1
        
        Box_matrix[x_cur, y_cur] = 1.0
       
    end

    Box_matrix
end 

Num_boxes_2D (generic function with 2 methods)

In [71]:
sum(Num_boxes_2D(CapDimData, 0.01, 1, 2))

13958.0

In [72]:
sum(Num_boxes_2D(CapDimData, 0.5, 1, 3))

4345.0

In [55]:
ceil(0)

0

In [30]:
ceil(Int, 28.442 + 25.715)

55

In [24]:
zeros(55)

55-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0